language: java
sudo: false
install: true
script: mvn clean package -DskipTests=true
deploy:
  provider: heroku
  api_key:
    secure: Xvbp8WfoTrwYyFtQZHIF0Mkr5vbn0SSyFstndm8yNH2M3FRohFwGiTnP3RDAkqMWs6h0kw/vPEHho2KiXmmnNNTgEPuhu+MVT1Oen1i7p3uc+5wItBivGalCDAELshiMeHbi3Uqwxq3AOIB9iv/xk/H30EjeG8BwQum4C01rNGDxG+jWqVdaek82gkaO+OQHNsQtmnjAPvZLpAaH0kIQZ3WiX1QJ2P/K8pprpOJjIrj5Kl9xARahfkfsojcxFmpkjy+OLVANJM9f3N/hO9JY9Ym+qU+ooX3c/DezxkG8IdcdbcNRnNYipgaEBI+BTEVKaGejF3bC0uoLXRB1xEVltAetx0VNtcjZWYxsBba/UCWgpjgd75YxOf9UdSm3sVbJr6iMXe5oPqROuOvPcpwA7gtQVhMa4HQ1NPrMjLog0w51hwF9S7gSjEotnhBu/UUHYUtlDuWG3P0PMRl27Bo5H/Z7E35xmXqhxiTKdeLdf2MvRj9wnCNNSxa8Tbf0NwycPjYprRcrtllbbBjX+gbcwqDFbmkFdN+iWqB0i4Q+33XKyzBse8BI4VwxqN2fI/fE4SbOV0QcVG4lO1d5VAaqYk4Gs/HNdbzYxCt2Tq+gLzKgZxnG0a/97xUP1b6GNMP7Chr32iKzgN1UE3UMGJYvNf4r71qzD5BDf28YPtjO4KQ=
  app: forum-4job
notifications:
  email:
    recipients: "-mrArxi@gmail.com"
on_success: never
on_failure: always
