language: java
sudo: false
install: true
script: mvn clean package -DskipTests=true
deploy:
  provider: heroku
  api_key:
    secure: X1R11I/kh4Aa0BfmSRL9c+j9N5jLqtSJ80ehNk33oLU65e/1jGpUuuxUYyPgXJBUJw6wITUcfhzhySNZsMKpSk/iDGN9lE6zKdSDa/VREBYtL2fJQxgKrA4/UGBINfZzo2s8aTHcDr6orf5cRcA/GSa76SNzoWSKMtsc+kQGWYwisv7s+yhm9t2uybPt4gbIR7NtU508Cw/xrxAXp4Kbw2B5ThNXKvVg7X+dVNDwXysKUeeia1RYWI7frmf/tbyxLbmpOAGHw1ZLuO9SlO1VrqRdFaxgwXf4KveYHKi1Q/rIM52JZ+76huDLQBBSd6yPRdFPg3/sjTPyK5QeUX+uQeHJFfb1fG3PomzqbyWdaHn4im5KS3W/5hANcftHyLTirkVaB9q+mFxiFYKMxX0Er0qwxrlEQ+Yb3AnBAqc886BkF4a8UqP8k1DdJj8WOAwNnxmX69FsxlLptOHvGN1bU5d6nZ81bGyoukpKSVHc+RirUbgwbz5noF8+3O343aEyoUdpFNw/M0Hd5C33vTlTjyLB0BSlr3nBXRxGShoovprLl8NQugacLOvCEj5HnOJiDtzIdY7bkl2ndbRDt3OJr4zTtI/m6RJcvWFm+xxct3f3cDr2ni2+Axi8yyjca0pGUMX0bKbnlCVa/vLf/rK2fTK/DZUdppcQsupyr7DQlwk=
  app: forum-4job
notifications:
  email:
    recipients: "-mrArxi@gmail.com"
on_success: never
on_failure: always
